package BasicClasses;

public enum BrowserTypes {
	
	//现有支持的浏览器类型
	  FIREFOX,FIREFOX_PROXY,FIREFOX_CHROME,GOOGLECHROME,SAFARI,OPERA
	  ,IEXPLORE,IEXPLORE_PROXY,SAFARI_PROXY,CHROME,KONQUEROR,MOCK,IE_HTA
	  ,ANDROID,HTMLUNIT,IE,IPHONE,IPAD,PHANTOMJS
}